- hosts: webserver
  become: yes
  remote_user: <Secret>
  vars:
    ansible_ssh_private_key_file: /opt/key.pem
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Pull WordPress Docker image
      docker_image:
        name: wordpress
        source: pull

    - name: Create WordPress environment file
      template:
        src: /opt/ansible-project/wordpress.env.j2
        dest: /opt/wordpress.env

    - name: Deploy MySQL container
      docker_container:
        name: mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "<Secret>"
          MYSQL_DATABASE: <Secret>
          MYSQL_USER: <Secret>
          MYSQL_PASSWORD: "<Secret>"
        volumes:
          - mysql-data:/var/lib/mysql
        restart_policy: always

    - name: Start WordPress container
      docker_container:
        name: wordpress
        image: wordpress
        env_file: /opt/wordpress.env
        ports:
          - "8080:80"
        restart_policy: always
        links: 
          - mysql
